### ISSUE TITLE
No folders/files in "actor-server/target/dist"

### ISSUE THREAD

**Issue by KitoHo** [actorapp/actor-platform#102]
I built actor server form Sources, but i could't find dist folder/file in "actor-server/target/"
Am i miss some steps for building?

**Comment by yashmurty** [comment]
I am also facing this issue.

**Comment by prettynatty** [comment]
We migrated to sbt-native-packager, it generated zip file in target/universal which contains a dist.

**Comment by ljshj** [comment]
For new building way, which is right for config file, application.conf or server.conf?

**Comment by prettynatty** [comment]
server.conf

**Comment by ljshj** [comment]
SERVER.md should be updated for config way, such as server.conf and application.ini ...

**Comment by prettynatty** [comment]
Already updated in #106
