### ISSUE TITLE
This Project Is Dead With No Support 

### ISSUE THREAD

**Issue by Elqul** [actorapp/actor-platform#1026]
Hello everyone.

this project is dead, and the app server doesnt work with alot of users. it crashes  and produces errors.

plus after trying to get support from this team, they didnt even respond even though i was willing to pay them.

So to new developers looking for a messaging system, take my advice. Dont use this platform unless you are a good Scala/ Akka developer.

Good Luck

**Comment by mohsenShakiba** [comment]
Totally agree, we have been playing around with it for 2 weeks worth of man-hour and we are still facing very basic errors and crashes.

**Comment by y0ke** [comment]
It'll be helpful if you could provide the detail situation to get clashed. such as number of registered users and peak message amount per min.
And I guess running it as server clustering might fix this issue though I'm not sure. if it's a database side problem, changing table layout or optimizing index might be needed.
