### ISSUE TITLE
Cannot install 3.0.0 server on Ubuntu 16.04

### ISSUE THREAD

**Issue by sorcer1122** [actorapp/actor-platform#1028]
Hello,

I have followed this manual https://developer.actor.im/docs/server-install

Here is what I got:

The following NEW packages will be installed
  actor
0 to upgrade, 1 to newly install, 0 to remove and 22 not to upgrade.
Need to get 111 MB of archives.
After this operation, 123 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  actor
Get:1 https://dl.bintray.com/actor/ubuntu trusty/main amd64 actor all 3.0.0 [111 MB]
Fetched 111 MB in 14s (7,852 kB/s)                                                                                                                       
Selecting previously unselected package actor.
(Reading database ... 287985 files and directories currently installed.)
Preparing to unpack .../archives/actor_3.0.0_all.deb ...
Unpacking actor (3.0.0) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up actor (3.0.0) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Failed to start actor.service: Unit actor.service not found.
actor could not be registered or started

Any idea what my cause this problem?

**Comment by unreg** [comment]
Ubuntu 16.04 have a systemd, not upstart.
You must a create systemd unit for start Actor server or run manually

**Comment by sorcer1122** [comment]
@unreg and how do I do it?

I also tried to run it manually via nohup bin/actor but the servers terminates after 5-10 seconds.

**Comment by unreg** [comment]
see error in log file

**Comment by unreg** [comment]
Or use quick start with docker https://developer.actor.im/docs/deployment

**Comment by sorcer1122** [comment]
@unreg many thanks, with Docker I installed it like a charm, however I am not able to activate any account. Via web: after entering email nothing happens. Via phone app: I get 'no provider found to hand code of type class im.actor.server.activation.common.Emailcode' error. 

Is it related to SMS token?

**Comment by unreg** [comment]
See /usr/share/actor/conf/server.conf.example for setup your e-mail registration.

**Comment by sorcer1122** [comment]
@unreg thanks, I do not have /usr/share/actor/conf folder. I created it manually and copied server.conf.minimal there, renamed it to server.conf and changed default settings but still no luck.

I have got Docker 1.12.1 build 23cf638

**Comment by sorcer1122** [comment]
For some strange reason after restarting Ubuntu machine, all Docker's containers were gone :(

**Comment by sorcer1122** [comment]
OK, now I am at least getting "GATE_ERROR" message for either phone or email registration. Where can I find server.conf in case of deployment via Docker?

**Comment by unreg** [comment]
Keep in touch with the Actor community https://actor.im/join/actor_oss

**Comment by sorcer1122** [comment]
Almost there...does anyone know where to find server.conf in case of Docker?

**Comment by amostajabi** [comment]
I've got the same problem with email activation... can you show me a sample
server.conf for activation using email?
Does it need the server to support ssl or is there any special dependancy
needed?
Thanks

**Comment by sorcer1122** [comment]
Great, my server works now. Read https://github.com/actorapp/actor-bootstrap/tree/master/docs and double check your server.conf
