### ISSUE TITLE
WebApp not working

### ISSUE THREAD

**Issue by sorcer1122** [actorapp/actor-platform#1029]
Hello guys,

I managed to get my server up and running along with haproxy, everything works smoothly with exception of WebApp.

I followed this manual - https://developer.actor.im/docs/web-sdk-getting-started

After I do gulp dev - everything seems to be ok but when I go to localhost:3000 I get a blank page, however I can see Actor's icon and page's name.

If I carry on and compile WebApp, put the content of dist folder to /var/www/html, I can see a big Actor's logo on the page but the actual webapp is not loading.

I have spent 2 full days playing around with it, nothing seems to work.

I have seen many people here managed to install it, so any help would be appreciated.

Thanks

**Comment by sorcer1122** [comment]
Anyone please????

**Comment by alashow** [comment]
You need to post some more details. For eg: logs from browser console.

**Comment by sorcer1122** [comment]
@alashow thanks! I get the following error in the console: ReferenceError: Can't find variable: _pace

**Comment by alashow** [comment]
I think this is related to https://github.com/HubSpot/pace/issues/200

**Comment by sorcer1122** [comment]
@alashow Gradually getting there but still there is another error - [Error] TypeError: m.default.start is not a function. (In 'm.default.start({ajax:!1,restartOnRequestAfter:!1,restartOnPushState:!1})', 'm.default.start' is undefined)

**Comment by sorcer1122** [comment]
The fix is here - https://github.com/actorapp/ActorSDK-Web/issues/3
