### ISSUE TITLE
Unable to deploy actor server when built from sources.

### ISSUE THREAD

**Issue by yashmurty** [actorapp/actor-platform#104]
The [documentation](https://github.com/actorapp/actor-platform/blob/master/SERVER.md) instructs to do the following
`Grab your server in actor-server/target/dist`

But there is no folder called dist.
The target folder has some .jar files, upon trying to execute them I get the following error
`Error: Could not find or load main class im.actor.server.Main`

Also there is a actor-server shell script in the target folder, upon trying to execute I get the same error again
`sudo ./actor-platform/actor-server/target/universal/tmp/bin/actor-server`
`Error: Could not find or load main class im.actor.server.Main`

**Comment by prettynatty** [comment]
We migrated to sbt-native-packager which generates dist in a different way. Updated readme.
