### ISSUE TITLE
Can't start it at all.

### ISSUE THREAD

**Issue by constantineSafronov** [actorapp/actor-platform#105]
1. Installed ./installDeps.sh ios 
2. installed pods 
3. Updated Java plugin

and than i have http://prntscr.com/8chzqz

**Comment by ex3ndr** [comment]
Try to clean Soruces folder, delete XCode derived data (```rm -fr ~/Library/Developer/Xcode/DerivedData```) and perform clean build.

What java plugin did you updated?

**Comment by constantineSafronov** [comment]
Resolved. Updated java and cleaned project.
