### ISSUE TITLE
iOS app crash on group typing at the same time

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#108]
When two member type in a group at the same time, the ios app will crash.
the ios log have a "JavaLangNullPointerException"
I trace it and find that it crash on line 163 of I18nEngine.java ,"return locale.get("TypingMultiple").replace("{count}", "" + count);"

I use NSLocalizedString(@"CurrentLocale",comment: @"Current Locale Value") for Chinese.

**Comment by prettynatty** [comment]
cc @ex3ndr

**Comment by ljshj** [comment]
It is in conversation view.

**Comment by ljshj** [comment]
Sorry, I found that this bug is my fault.  
The AppText _Cn.properties which is contributed by me have two wrong blanks:
TypingMultiple = {count}个人正在输入... 
It should be corrected to:
TypingMultiple={count}个人正在输入...

Please update it.Thanks.
