### ISSUE TITLE
(Bug) Push notification is sent when the recipient is still online

### ISSUE THREAD

**Issue by nchiring** [actorapp/actor-platform#110]
Currently when a sender pings a message, server pushes the message as a push notification also even though the recipient is still online and actively chatting. The pn is being suppressed by the client code( Android) though if the recipient is online. However, this is a bug. A pn is being wasted unnecessarily.

**Comment by ex3ndr** [comment]
When you use actively in other chat and there come a lot of messages, you don't need to see notifications and play sounds: unread indicator on top might be enought, isn't it?

**Comment by nchiring** [comment]
What you are suggesting works and this is how it is being handled currently, suppress the PN if the user( recipient) is online. However, server shouldn't send the PN in first place if the recipient is online.
