### ISSUE TITLE
In iOS9, Chinese keyboard will cover input box

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#114]
In iOS9,first time to go into conversation view, Chinese keyboard will cover input box .
![image](https://cloud.githubusercontent.com/assets/1897715/9977060/cf8a59b6-5f2c-11e5-8cad-92ae8128471a.png)

**Comment by ex3ndr** [comment]
Does this appear always?

**Comment by ljshj** [comment]
Yes, it always appear when you go into conversation view first time. If you can back to dialogs view and go into coversation view again， it will be ok.

**Comment by ljshj** [comment]
The keyboard is Chinese system default keyboard named "Chinese (Simplified) - Pinyin"

**Comment by ex3ndr** [comment]
Does this work with only chinese? or just in ios9 or something like?

**Comment by ljshj** [comment]
If system is <iOS 9 , All is ok for Chinese keyboard. Just in iOS 9 the Chinese Pinyin keyboard will cover the input box.

**Comment by ljshj** [comment]
The old SlackTextViewController has same problem. Today, I test latest SlackTextViewController, it have been OK.

**Comment by liruqi** [comment]
It's fixed now. This issue can be closed.
