### ISSUE TITLE
Status.Failure potentially called twice

### ISSUE THREAD

**Issue by ddispaltro** [actorapp/actor-platform#115]
Doesn't this look like a bug?

https://github.com/actorapp/actor-platform/blob/fc27b9e24fc0baffb4887bae318dfcfb9f679424/actor-server/actor-core/src/main/scala/im/actor/server/office/Processor.scala#L122

Since pipeTo will already handle sending a `Status.Failure` to the actor.  I haven't experienced anything I was just looking through the code.

**Comment by prettynatty** [comment]
Good point, it should be fixed. Thanks.
