### ISSUE TITLE
Marketing/example images need revision

### ISSUE THREAD

**Issue by halostatue** [actorapp/actor-platform#117]
I’m certain that the discussion in the marketing images actually happened, but it seems to be questionable judgement to include a discussion subject that seems to exemplify techie sexism by talking about “two hot naked girls”:

![](https://raw.githubusercontent.com/actorapp/actor-platform/master/actor-resources/screenshots/Android1_Small.jpg)

I’d have a hard time encouraging women in tech to visit the Actor website and get involved with this subject present so prominently in the images (and the main marketing image has it replicated in two places (the Android device and the iPad).

**Comment by jamesbond12** [comment]
Haha I wouldn't agree with you more 😊

**Comment by ljshj** [comment]
😄

**Comment by ex3ndr** [comment]
I will take care about this, but really don't understand where is sexism. Why straight student of Harvard can't say this? Also this is quote from film "Pirates of silicon valley".

**Comment by halostatue** [comment]
@ex3ndr: Thanks for looking at this. This is certainly something that someone *could* say in a chat—and in some places certainly *would*, but the question I’m raising is whether or not you want a woman to come to your marketing site and dismiss the use of Actor entirely because they see what they feel to be unnecessary sexism presented and would assume that they are not welcome in the Actor community. (It’s not just women, by the way; I pointed this out to a colleague in real life and he expressed concern as well.)

I will freely admit that I have not seen “Pirates of Silicon Valley”, but that line seems to be representing a Valley that shouldn’t be celebrated in today’s world. It’s very much “frat-boy” in a way that excludes women except as sex objects.

At any rate, I do want to thank you for reconsidering this—it’s a small thing, but I think that there are lots of other quotes that could be used without introducing an unintentional barrier. (Scenes from _Monty Python and the Holy Grail_ or _The Hitchhiker’s Guide to the Galaxy_ would not be amiss and probably go over as well.)

**Comment by halostatue** [comment]
:+1: for the changes here. Thank you again for being open to this suggested change.
