### ISSUE TITLE
compile error within intellij

### ISSUE THREAD

**Issue by narychen** [actorapp/actor-platform#122]
I could build and run the actor-server directly in sbt console.  sbt run sbt compile what ever.. It's ok. No problem. But when I imported the project into intellij using build.sbt, I got compile error and my intellij editor  could not resolve this symbol.

/Users/nary/Desktop/entry/actor-platform/actor-server/actor-runtime/src/main/scala/im/actor/serialization/ActorSerializer.scala

Error:(45, 44) not found: value SerializedMessage
    val SerializedMessage(id, bodyBytes) = SerializedMessage.parseFrom(bytes)
                                           ^
Error:(45, 9) not found: value SerializedMessage
    val SerializedMessage(id, bodyBytes) = SerializedMessage.parseFrom(bytes)
        ^
Error:(49, 27) value getField is not a member of Any
        val field = clazz.getField("MODULE$").get(null)
                          ^
Error:(52, 12) value getDeclaredMethod is not a member of Any
possible cause: maybe a semicolon is missing before `value getDeclaredMethod'?
          .getDeclaredMethod("validate", ARRAY_OF_BYTE_ARRAY: _*)
           ^
Error:(65, 39) not found: value SerializedMessage
          case m: GeneratedMessage  ⇒ SerializedMessage(id, ByteString.copyFrom(m.toByteArray)).toByteArray
                                      ^
Error:(66, 39) not found: value SerializedMessage
          case m: GGeneratedMessage ⇒ SerializedMessage(id, ByteString.copyFrom(m.toByteArray)).toByteArray
                                      ^

**Comment by prettynatty** [comment]
It is an Intellij Idea bug. It does not handle generated sources correctly.

**Comment by narychen** [comment]
If so, how can I build and debug the code through Intellij?
Do you guys use Intellij or other IDE?
I see .gitignore has some excluding lines with .idea, so I guess you use Intellij too.

**Comment by narychen** [comment]
I use the sbt command line to generate the protobuf scala code.
Now it compiles with error "already defined ..." .
I searched the word and only saw it defined here. Why intellij complains about it?

/Users/nary/Desktop/entry/actor-platform/actor-server/actor-runtime/target/src_managed/main/compiled_protobuf/im/actor/serialization/SerializationProto.scala
Error:(11, 8) SerializationProto is already defined as object SerializationProto
object SerializationProto {
       ^
/Users/nary/Desktop/entry/actor-platform/actor-server/actor-runtime/target/src_managed/main/compiled_protobuf/im/actor/serialization/SerializedMessage.scala
Error:(12, 18) SerializedMessage is already defined as case class SerializedMessage
final case class SerializedMessage(
                 ^
Error:(58, 8) SerializedMessage is already defined as object SerializedMessage
object SerializedMessage extends com.trueaccord.scalapb.GeneratedMessageCompanion[SerializedMessage]  {
       ^

**Comment by narychen** [comment]
Hey, guys. I finally solved it myself.
There is a make option in the intellij's run/debug configuration "before lunch". Delete it and Intellij will not do make before you lunch the sbt. So it will not report error as I mentioned above.

**Comment by ksngits** [comment]
![screenshot from 2015-10-06 18 05 13](https://cloud.githubusercontent.com/assets/13203949/10305757/e1ea98e8-6c54-11e5-9462-bc8f2a062d07.png)


Attached the supporting screen shot for the comments  by @narychen

**Comment by prettynatty** [comment]
Some references here
* http://stackoverflow.com/questions/16885489/intellij-compile-failures-is-already-defined-as
* https://youtrack.jetbrains.com/issue/SCL-7835

**Comment by prettynatty** [comment]
https://youtrack.jetbrains.com/issue/SCL-9301#tab=Linked%20Issues
