### ISSUE TITLE
 compile error within intellij 2

### ISSUE THREAD

**Issue by ksngits** [actorapp/actor-platform#123]
I am able to compile using sbt dist, but get the following error, when I compile using Intellij IDE?
Any ideas?

I have Google protobuf installed and the version 2.6.1

$protoc --version
libprotoc 2.6.1

File: actor-server/actor-runtime/target/src_managed/main/compiled_protobuf/im/actor/serialization/SerializationProto.scala

Error:(11, 8) SerializationProto is already defined as object SerializationProto
object SerializationProto {
       ^
/opt/ext/actor-platform/actor-server/actor-runtime/target/src_managed/main/compiled_protobuf/im/actor/serialization/SerializedMessage.scala
Error:(12, 18) SerializedMessage is already defined as case class SerializedMessage
final case class SerializedMessage(
                 ^
Error:(58, 8) SerializedMessage is already defined as object SerializedMessage
object SerializedMessage extends com.trueaccord.scalapb.GeneratedMessageCompanion[SerializedMessage]  {
       ^

**Comment by prettynatty** [comment]
As I said in #122, it's Intellij Idea problem, it does not handle generated sources properly.
