### ISSUE TITLE
new build system missing files?

### ISSUE THREAD

**Issue by razeghi71** [actorapp/actor-platform#132]
Hi

I just noticed that you reorganized your build system.
but I think there are some missing build.gradle and settings.gradle files to connect actor-app and actor-sdk?
Am I right?

**Comment by ex3ndr** [comment]
This feature is work in progress. actor-app shouldn't be dependent on sdk directly, but with maven depdendency

**Comment by atulkapoor** [comment]
Can you guys also update the docs?

**Comment by ex3ndr** [comment]
We will update everything as it will be ready. Until this use v0.9
