### ISSUE TITLE
Not Building in Xcode 7.0.1 with Swift 2.0

### ISSUE THREAD

**Issue by PikadotiOS** [actorapp/actor-platform#139]
I have downloaded the code and made setup as instructed but I am not able to build the code.

Can you please help me out in building the code ?

**Comment by narychen** [comment]
you have to do follow the instruction on https://actor.readme.io/v1.0/docs/ios-app
I just built it with xcode 7.0.1 . No problem met.

**Comment by PikadotiOS** [comment]
Did you convert the code to latest swift syntax ? Because I am getting around 10 errors.

Can you send me the dropbox link of your code ?

**Comment by narychen** [comment]
I just downloaded the code from here. I didn't modify anything.

**Comment by PikadotiOS** [comment]
I have done the same thing but still I am facing issue.

Here's the image : http://postimg.org/image/4ezzb1hgn/

After downloading the code, did you convert the code in xcode ? And specific settings have you made in Xcode ?

**Comment by PikadotiOS** [comment]
If you are able to build the code then please send me the same folder with build. Because I am not able to figure out what the problem is and why the code is not being build.
