### ISSUE TITLE
v0.9 server install error

### ISSUE THREAD

**Issue by atulkapoor** [actorapp/actor-platform#140]
actor -v throws error

actor -v
# Executing command line:
java
-Dconfig.file=/usr/share/actor/bin/../conf/server.conf
-Dlogback.configurationFile=/usr/share/actor/bin/../conf/logback.xml
-Xms256M
-Xmx1024M
-cp
/usr/share/actor/lib/actor.actor-1.0.53.jar:/usr/share/actor/lib/actor-runner.actor-runner-1.0.53.jar:/usr/share/actor/lib/actor-activation.actor-activation-1.0.53.jar:/usr/share/actor/lib/actor-email.actor-email-1.0.53.jar:/usr/share/actor/lib/actor-sms.actor-sms-1.0.53.jar:/usr/share/actor/lib/actor-runtime.actor-runtime-1.0.53.jar:/usr/share/actor/lib/actor-persist.actor-persist-1.0.53.jar:/usr/share/actor/lib/actor-models.actor-models-1.0.53.jar:/usr/share/actor/lib/actor-bot.actor-bot-1.0.53.jar:/usr/share/actor/lib/im.actor.actor-bot-shared-1.0.53.jar:/usr/share/actor/lib/shardakka.shardakka-1.0.53.jar:/usr/share/actor/lib/actor-core.actor-core-1.0.53.jar:/usr/share/actor/lib/actor-codecs.actor-codecs-1.0.53.jar:/usr/share/actor/lib/actor-presences.actor-presences-1.0.53.jar:/usr/share/actor/lib/actor-social.actor-social-1.0.53.jar:/usr/share/actor/lib/actor-enrich.actor-enrich-1.0.53.jar:/usr/share/actor/lib/actor-rpc-api.actor-rpc-api-1.0.53.jar:/usr/share/actor/lib/actor-oauth.actor-oauth-1.0.53.jar:/usr/share/actor/lib/actor-session-messages.actor-session-messages-1.0.53.jar:/usr/share/actor/lib/actor-frontend.actor-frontend-1.0.53.jar:/usr/share/actor/lib/actor-session.actor-session-1.0.53.jar:/usr/share/actor/lib/actor-http-api.actor-http-api-1.0.53.jar:/usr/share/actor/lib/actor-notifications.actor-notifications-1.0.53.jar:/usr/share/actor/lib/com.trueaccord.scalapb.scalapb-runtime_2.11-0.5.14.jar:/usr/share/actor/lib/com.github.kxbmap.configs_2.11-0.2.4.jar:/usr/share/actor/lib/org.scala-lang.modules.scala-java8-compat_2.11-0.5.0.jar:/usr/share/actor/lib/ch.qos.logback.logback-classic-1.1.2.jar:/usr/share/actor/lib/com.typesafe.scala-logging.scala-logging_2.11-3.1.0.jar:/usr/share/actor/lib/tyrex.tyrex-1.0.1.jar:/usr/share/actor/lib/org.apache.commons.commons-email-1.4.jar:/usr/share/actor/lib/com.github.dnvriend.akka-persistence-jdbc_2.11-1.1.7.jar:/usr/share/actor/lib/com.github.ben-manes.caffeine.caffeine-1.2.0.jar:/usr/share/actor/lib/org.spire-math.cats_2.11-0.2.0.jar:/usr/share/actor/lib/com.googlecode.concurrentlinkedhashmap.concurrentlinkedhashmap-lru-1.4.2.jar:/usr/share/actor/lib/com.googlecode.libphonenumber.libphonenumber-7.0.11.jar:/usr/share/actor/lib/net.databinder.dispatch.dispatch-core_2.11-0.11.2.jar:/usr/share/actor/lib/com.eaio.uuid.uuid-3.4.jar:/usr/share/actor/lib/org.scodec.scodec-core_2.11-1.8.1.jar:/usr/share/actor/lib/com.github.tminglei.slick-pg_2.11-0.9.0.jar:/usr/share/actor/lib/com.github.tototoshi.slick-joda-mapper_2.11-2.0.0.jar:/usr/share/actor/lib/com.typesafe.slick.slick-testkit_2.11-3.0.3.jar:/usr/share/actor/lib/org.flywaydb.flyway-core-3.1.jar:/usr/share/actor/lib/com.zaxxer.HikariCP-2.3.5.jar:/usr/share/actor/lib/de.heikoseeberger.akka-http-play-json_2.11-1.0.0.jar:/usr/share/actor/lib/com.lihaoyi.upickle_2.11-0.3.6.jar:/usr/share/actor/lib/com.typesafe.akka.akka-contrib_2.11-2.3.13.jar:/usr/share/actor/lib/com.amazonaws.aws-java-sdk-s3-1.9.31.jar:/usr/share/actor/lib/com.github.dwhjames.aws-wrap_2.11-0.7.2.jar:/usr/share/actor/lib/com.google.android.gcm.gcm-server-1.0.2.jar:/usr/share/actor/lib/com.relayrides.pushy-0.4.3.jar:/usr/share/actor/lib/com.sksamuel.scrimage.scrimage-core_2.11-1.4.2.jar:/usr/share/actor/lib/com.typesafe.akka.akka-slf4j_2.11-2.3.13.jar:/usr/share/actor/lib/org.bouncycastle.bcprov-jdk15on-1.50.jar:/usr/share/actor/lib/org.scalaz.scalaz-concurrent_2.11-7.1.1.jar:/usr/share/actor/lib/com.google.protobuf.protobuf-java-3.0.0-alpha-3.jar:/usr/share/actor/lib/com.trueaccord.lenses.lenses_2.11-0.4.1.jar:/usr/share/actor/lib/ch.qos.logback.logback-core-1.1.2.jar:/usr/share/actor/lib/com.sun.mail.javax.mail-1.5.2.jar:/usr/share/actor/lib/com.typesafe.akka.akka-http-experimental_2.11-1.0.jar:/usr/share/actor/lib/commons-codec.commons-codec-1.10.jar:/usr/share/actor/lib/org.scalikejdbc.scalikejdbc_2.11-2.2.7.jar:/usr/share/actor/lib/com.typesafe.akka.akka-persistence-experimental_2.11-2.3.13.jar:/usr/share/actor/lib/com.github.ben-manes.caffeine.tracing-api-1.2.0.jar:/usr/share/actor/lib/org.spire-math.cats-state_2.11-0.2.0.jar:/usr/share/actor/lib/org.spire-math.cats-laws_2.11-0.2.0.jar:/usr/share/actor/lib/com.ning.async-http-client-1.8.10.jar:/usr/share/actor/lib/com.eaio.grabbag-1.8.1.jar:/usr/share/actor/lib/org.scodec.scodec-bits_2.11-1.0.9.jar:/usr/share/actor/lib/com.chuusai.shapeless_2.11-2.2.4.jar:/usr/share/actor/lib/com.github.tminglei.slick-pg_core_2.11-0.9.0.jar:/usr/share/actor/lib/com.novocode.junit-interface-0.11.jar:/usr/share/actor/lib/junit.junit-dep-4.10.jar:/usr/share/actor/lib/com.typesafe.slick.slick-codegen_2.11-3.0.3.jar:/usr/share/actor/lib/javax.inject.javax.inject-1.jar:/usr/share/actor/lib/org.javassist.javassist-3.19.0-GA.jar:/usr/share/actor/lib/com.typesafe.play.play-json_2.11-2.4.2.jar:/usr/share/actor/lib/org.spire-math.jawn-parser_2.11-0.7.0.jar:/usr/share/actor/lib/com.lihaoyi.derive_2.11-0.3.6.jar:/usr/share/actor/lib/com.typesafe.akka.akka-cluster_2.11-2.3.13.jar:/usr/share/actor/lib/com.amazonaws.aws-java-sdk-kms-1.9.31.jar:/usr/share/actor/lib/com.googlecode.json-simple.json-simple-1.1.1.jar:/usr/share/actor/lib/io.netty.netty-all-4.0.26.Final.jar:/usr/share/actor/lib/ar.com.hjg.pngj-2.0.1.jar:/usr/share/actor/lib/com.drewnoakes.metadata-extractor-2.6.2.jar:/usr/share/actor/lib/commons-io.commons-io-2.4.jar:/usr/share/actor/lib/com.twelvemonkeys.imageio.imageio-jpeg-3.0-rc5.jar:/usr/share/actor/lib/com.twelvemonkeys.imageio.imageio-core-3.0-rc5.jar:/usr/share/actor/lib/com.twelvemonkeys.common.common-lang-3.0-rc5.jar:/usr/share/actor/lib/org.apache.sanselan.sanselan-0.97-incubator.jar:/usr/share/actor/lib/org.scalaz.scalaz-effect_2.11-7.1.1.jar:/usr/share/actor/lib/org.scalaz.scalaz-core_2.11-7.1.1.jar:/usr/share/actor/lib/javax.activation.activation-1.1.1.jar:/usr/share/actor/lib/com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:/usr/share/actor/lib/org.scalikejdbc.scalikejdbc-interpolation_2.11-2.2.7.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-all-1.7.jar:/usr/share/actor/lib/org.iq80.leveldb.leveldb-0.5.jar:/usr/share/actor/lib/org.spire-math.cats-free_2.11-0.2.0.jar:/usr/share/actor/lib/org.spire-math.algebra-laws_2.11-0.3.1.jar:/usr/share/actor/lib/com.google.code.findbugs.jsr305-3.0.0.jar:/usr/share/actor/lib/org.postgresql.postgresql-9.4-1201-jdbc41.jar:/usr/share/actor/lib/com.typesafe.slick.slick_2.11-3.0.3.jar:/usr/share/actor/lib/junit.junit-4.11.jar:/usr/share/actor/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.5.4.jar:/usr/share/actor/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.5.4.jar:/usr/share/actor/lib/com.typesafe.play.play-datacommons_2.11-2.4.2.jar:/usr/share/actor/lib/com.typesafe.play.play-functional_2.11-2.4.2.jar:/usr/share/actor/lib/com.typesafe.play.play-iteratees_2.11-2.4.2.jar:/usr/share/actor/lib/com.typesafe.akka.akka-remote_2.11-2.3.13.jar:/usr/share/actor/lib/com.amazonaws.aws-java-sdk-core-1.9.31.jar:/usr/share/actor/lib/xerces.xercesImpl-2.8.1.jar:/usr/share/actor/lib/com.adobe.xmp.xmpcore-5.1.2.jar:/usr/share/actor/lib/com.twelvemonkeys.imageio.imageio-metadata-3.0-rc5.jar:/usr/share/actor/lib/io.netty.netty-3.9.2.Final.jar:/usr/share/actor/lib/org.scala-lang.modules.scala-xml_2.11-1.0.2.jar:/usr/share/actor/lib/joda-time.joda-time-2.8.2.jar:/usr/share/actor/lib/com.typesafe.akka.akka-stream-experimental_2.11-1.0.jar:/usr/share/actor/lib/com.typesafe.akka.akka-parsing-experimental_2.11-1.0.jar:/usr/share/actor/lib/org.scalikejdbc.scalikejdbc-interpolation-macro_2.11-2.2.7.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-win64-1.5.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-win32-1.5.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-linux64-1.5.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-linux32-1.5.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-osx-1.5.jar:/usr/share/actor/lib/com.google.guava.guava-12.0.jar:/usr/share/actor/lib/org.spire-math.algebra-macros_2.11-0.3.1.jar:/usr/share/actor/lib/org.typelevel.discipline_2.11-0.4.jar:/usr/share/actor/lib/org.spire-math.cats-core_2.11-0.2.0.jar:/usr/share/actor/lib/org.hamcrest.hamcrest-core-1.3.jar:/usr/share/actor/lib/com.fasterxml.jackson.core.jackson-databind-2.5.4.jar:/usr/share/actor/lib/org.scala-stm.scala-stm_2.11-0.7.jar:/usr/share/actor/lib/org.uncommons.maths.uncommons-maths-1.2.2a.jar:/usr/share/actor/lib/org.apache.httpcomponents.httpclient-4.3.4.jar:/usr/share/actor/lib/xml-apis.xml-apis-1.3.03.jar:/usr/share/actor/lib/com.twelvemonkeys.common.common-image-3.0-rc5.jar:/usr/share/actor/lib/com.typesafe.akka.akka-actor_2.11-2.3.13.jar:/usr/share/actor/lib/org.reactivestreams.reactive-streams-1.0.0.jar:/usr/share/actor/lib/org.scalikejdbc.scalikejdbc-core_2.11-2.2.7.jar:/usr/share/actor/lib/org.fusesource.leveldbjni.leveldbjni-1.7.jar:/usr/share/actor/lib/org.scalacheck.scalacheck_2.11-1.12.4.jar:/usr/share/actor/lib/org.spire-math.cats-macros_2.11-0.2.0.jar:/usr/share/actor/lib/com.fasterxml.jackson.core.jackson-annotations-2.5.4.jar:/usr/share/actor/lib/com.fasterxml.jackson.core.jackson-core-2.5.4.jar:/usr/share/actor/lib/org.apache.httpcomponents.httpcore-4.3.2.jar:/usr/share/actor/lib/commons-logging.commons-logging-1.1.3.jar:/usr/share/actor/lib/com.twelvemonkeys.common.common-io-3.0-rc5.jar:/usr/share/actor/lib/com.typesafe.config-1.3.0.jar:/usr/share/actor/lib/org.slf4j.slf4j-api-1.7.12.jar:/usr/share/actor/lib/org.scala-lang.modules.scala-parser-combinators_2.11-1.0.4.jar:/usr/share/actor/lib/org.joda.joda-convert-1.7.jar:/usr/share/actor/lib/commons-dbcp.commons-dbcp-1.4.jar:/usr/share/actor/lib/org.fusesource.hawtjni.hawtjni-runtime-1.8.jar:/usr/share/actor/lib/org.iq80.leveldb.leveldb-api-0.5.jar:/usr/share/actor/lib/org.scala-sbt.test-interface-1.0.jar:/usr/share/actor/lib/org.typelevel.machinist_2.11-0.4.1.jar:/usr/share/actor/lib/org.spire-math.algebra-std_2.11-0.3.1.jar:/usr/share/actor/lib/com.github.mpilquist.simulacrum_2.11-0.4.0.jar:/usr/share/actor/lib/org.scala-lang.scala-reflect-2.11.7.jar:/usr/share/actor/lib/commons-pool.commons-pool-1.5.4.jar:/usr/share/actor/lib/org.spire-math.algebra_2.11-0.3.1.jar:/usr/share/actor/lib/org.scala-lang.scala-library-2.11.7.jar
im.actor.server.Main

16:33:00,534 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/usr/share/actor/bin/../conf/logback.xml] at [file:/usr/share/actor/bin/../conf/logback.xml]
16:33:00,635 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:33:00,640 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 20 seconds
16:33:00,640 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/usr/share/actor/bin/../conf/logback.xml]] every 20 seconds. 
16:33:00,640 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
16:33:00,646 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.compiler] to WARN
16:33:00,646 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.ast] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka.stream.impl] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.zookeeper.ClientCnxn] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.relational.ResultConverterCompiler] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.jdbc.StatementInvoker.result] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.jdbc.JdbcBackend.statement] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.backend.DatabaseComponent.action] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick.jdbc.JdbcBackend.benchmark] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [im.actor.server.session.ReSender] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [im.actor.server.session.SessionMessagePublisher] to WARN
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [im.actor.server.peermanagers.GroupPeerManager] to INFO
16:33:00,647 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka.contrib.pattern.ShardRegion] to INFO
16:33:00,647 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:33:00,650 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [file]
16:33:00,723 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use gz compression
16:33:00,724 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/archive/server_%d{yyyy-MM,aux}/%d-%i.log for the active file
16:33:00,727 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f872068 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/archive/server_%d{yyyy-MM,aux}/%d-%i.log.gz'.
16:33:00,727 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f872068 - Roll-over at midnight.
16:33:00,730 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f872068 - Setting initial period to Sun Oct 18 16:21:56 UTC 2015
16:33:00,732 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@30:20 - no applicable action for [withJansi], current ElementPath  is [[configuration][appender][withJansi]]
16:33:00,732 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:33:00,750 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - Active log file name: logs/server.log
16:33:00,750 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - File property is set to [logs/server.log]
16:33:00,751 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
16:33:00,751 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [file] to Logger[ROOT]
16:33:00,752 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:33:00,752 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2ef384e9 - Registering current configuration as safe fallback point

Exception in thread "main" org.jboss.netty.channel.ChannelException: Failed to bind to: /172.31.26.249:2552
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:393)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:389)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] [10/18/2015 16:33:01.028] [actor-server-akka.remote.default-remote-dispatcher-5] [Remoting] Remoting system has been terminated abrubtly. Attempting to shut down transports

**Comment by prettynatty** [comment]
You have another actor server instance running.
