### ISSUE TITLE
Why cant use actor in Android 4.0.3 - 

### ISSUE THREAD

**Issue by l3l4c7-h4t** [actorapp/actor-platform#142]
Hi,
I want to make Messaging Application and i want to use Actor SDK.

but i saw this sdk is only worked in the Android 4.0.3+.

so, can i change the source code or remove some Property of the Actor for working in the Android 4.0.3- ?

Best Regards

**Comment by ex3ndr** [comment]
On such stage of a project it is non-sense to support 4+ year old operating system. People who have such phones will never install our app.
