### ISSUE TITLE
Problems with notifications

### ISSUE THREAD

**Issue by alessandrofeitoza** [actorapp/actor-platform#143]
Problems in mobile, they are showing problems with notifications, not always the same reach.

**Comment by ex3ndr** [comment]
What platform?

**Comment by alessandrofeitoza** [comment]
Hi, in Mobile... 




De: "Steve Kite" <notifications@github.com> 
Para: "actorapp/actor-platform" <actor-platform@noreply.github.com> 
Cc: "Alessandro Feitoza" <eu@alessandrofeitoza.eu> 
Enviadas: Segunda-feira, 26 de outubro de 2015 17:44:21 
Assunto: Re: [actor-platform] Problems with notifications (#143) 



What platform?

**Comment by ex3ndr** [comment]
iOS/ Android?

**Comment by liruqi** [comment]
![img_0793](https://cloud.githubusercontent.com/assets/244492/10779356/87fa87cc-7d6a-11e5-80a7-ce6fbc9fdd46.jpg)

In my case, iOS notifications are duplicated.

**Comment by rockjam** [comment]
Is this still actual?

**Comment by liruqi** [comment]
@rockjam should be fixed now.
