### ISSUE TITLE
ActorSDK for iOS - a set of ViewControllers and Views

### ISSUE THREAD

**Issue by alxon** [actorapp/actor-platform#150]
Developer can pick up UI components from this set and insert them into their application storyboard or code

**Comment by ex3ndr** [comment]
You already can do this. But we don't use storyboards.

**Comment by feliu** [comment]
why you don't use storyboards?

**Comment by ex3ndr** [comment]
I have no idea how storyboard can help me in development. We don't use xibs even as they are slow to load - for loading controller you need to read xib from disk, this is not that fast.

**Comment by alxon** [comment]
I'm not talking about the "use StoryBoard"

Read the documentation: (https://actor.readme.io/docs/ios-sdk-getting-started)
"INTEGRATION IN YOUR APP
Now you can import ActorSDK module and get access to ActorSDK class. In your UIApplicationDelegate in didFinishLaunch method call this two methods
ActorSDK.sharedActor (). CreateActor ()
ActorSDK.sharedActor (). PresentInNewWindow ()
RUN
That's all! Press run and you will see Actor messenger running in your app "

As a result, it reassigns UIWindow.rootViewController

But I do not need to touch rootViewController
I want "INTEGRATION IN YOUR APP", I need to display the chat window in (for example) UITabBarController

PS first attempt was strange
Navigations.swift
public func navigateDetail (controller: UIViewController) {
        if (AADevice.isiPad) {
            let split = UIApplication.sharedApplication (). keyWindow? .rootViewController as! UISplitViewController
What causes an error (if "rootViewController" not "UISplitViewController")

**Comment by ex3ndr** [comment]
You need to implement methods in subclass of ActorSDKDelegate and pass it to ActorSDK instance

**Comment by alxon** [comment]
Did I understand correctly?
It is necessary to fully realize all the controllers
AAContactsViewController
AARecentViewController
AASettingsViewController
AAAuthPhoneViewController
and so on

Because
1 AAContactsViewController - not public
2 AARecentViewController and some others - require UISplitViewController (in rootViewController for iPad)
3 ...

I made a mistake somewhere or misunderstood !? (I use a pod)
Where can I take the example of how to implement a chat in a separate UIView (not UIWindow)?

**Comment by ex3ndr** [comment]
Why you need to implement all of them? Return null when you don't want to override. Subclass from ActorSDKDelegateDefault as it have default implementations (empty one)

**Comment by alxon** [comment]
we are talking about the same thing?
I can override authorization
But after that ...
if I will return null, I get AARootSplitViewController in window.rootViewController
(iPad version)

-----------------
public func presentMessengerInWindow(window: UIWindow) {
        ...
        self.bindedToWindow = window
            ...
            var controller: UIViewController! = delegate.actorControllerForStart()
            if controller == nil {
                let tab = AARootTabViewController()
                tab.viewControllers = [
                    AANavigationController(rootViewController: AAContactsViewController()),
                    AANavigationController(rootViewController: AARecentViewController()),
                    AANavigationController(rootViewController: AASettingsViewController())]
                tab.selectedIndex = 0
                tab.selectedIndex = 1
                
                if (AADevice.isiPad) {
                    let splitController = AARootSplitViewController()
                    splitController.viewControllers = [tab, AANoSelectionViewController()]
                    controller = splitController
                } else {
                    controller = tab
                }
            }
            window.rootViewController = controller!

**Comment by alxon** [comment]
Is there anyone alive?

**Comment by ex3ndr** [comment]
I don't understand what are you talking about

**Comment by alxon** [comment]
Look here please
https://github.com/alxon/testActorSDK
