### ISSUE TITLE
[iOS SDK] On Launch blank screen.

### ISSUE THREAD

**Issue by hashg** [actorapp/actor-platform#160]
I built this sample project to test sdk - https://github.com/hashg/ActorSDKApp.
When I launch it in simulator or on the phone it only show a numpad keyboard on a blank screen

![img_1745](https://cloud.githubusercontent.com/assets/309076/11058009/a36d6f2c-8744-11e5-8d86-84203aa58823.PNG)

**Comment by ru-kio** [comment]
@hashg try now, it's work fine.
