### ISSUE TITLE
[iOS SDK] Min version is 8.0

### ISSUE THREAD

**Issue by hashg** [actorapp/actor-platform#161]
As per the README it is indicated that iOS min version for actor is 7.0+. 
But when building [SDK app](https://github.com/hashg/ActorSDKApp) on 7.0 target. It throws this error.

```
ActorSDKApp/ActorSDKApp/AppDelegate.swift:10:8: 
error: module file's minimum deployment target is ios8.0 v8.0: 
ActorSDKApp/Pods/ActorSDK-iOS/Frameworks/ActorSDK.framework/Modules/ActorSDK.swiftmodule/arm.swiftmodule
```

**Comment by ex3ndr** [comment]
We don't support iOS 7 anymore.
