### ISSUE TITLE
One message push Three ios notification when app is in background

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#168]
With latest server code, One message push Three ios notification when ios app is in background.

Sometime, the ios notification push is twice. 

When The ios app has been killed, it  is same.

Maybe, I think server use expired ios pus token and new token , they both can be sent for some time. I guess.

**Comment by prettynatty** [comment]
Did you reinstall app on the device with that problem?

**Comment by ljshj** [comment]
Yes, I reinstalled ios app. But sometime the  push  is twice, sometime the push is three times.

**Comment by xzenon** [comment]
I have the same issue.
