### ISSUE TITLE
web-app: EPEERINVALID when building

### ISSUE THREAD

**Issue by markcs** [actorapp/actor-platform#170]
The web-app fails to build with the following error:

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.13.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.10.1 wants react@>=0.13
npm ERR! peerinvalid Peer react-modal@0.3.0 wants react@>=0.13.3
npm ERR! peerinvalid Peer react-router@0.13.3 wants react@0.13.x
npm ERR! peerinvalid Peer react-scroll@0.0.1 wants react@^0.13.3
npm ERR! peerinvalid Peer react-visibility-sensor@2.1.0 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.1 wants react@^0.14.0

Debug log attached.

[npm-debug.txt](https://github.com/actorapp/actor-platform/files/45566/npm-debug.txt)

**Comment by olegshilov** [comment]
We use npm@3.
Just upgrade npm with `npm update -g npm`

**Comment by markcs** [comment]
Thanks. That fixed it.
