### ISSUE TITLE
No close icon is on photo preview view of ios app.

### ISSUE THREAD

**Issue by ljshjlsx** [actorapp/actor-platform#183]
No close icon is on photo preview view of ios app. It should be on the left top.

**Comment by liruqi** [comment]
It's a bug on NYTPhotoViewer
To fix for now, replace `pod 'NYTPhotoViewer'` with `pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer', :branch => 'feature/close-button'`
or 
`pod 'NYTPhotoViewer', :git => 'https://github.com/liruqi/NYTPhotoViewer', :branch => 'develop'`

**Comment by kioshimafx** [comment]
Thx @liruqi

**Comment by liruqi** [comment]
@kioshimafx I suggest you fork NYTPhotoViewer and maintain it for actor-platform. It's painful to wait for other to fix and update to CocoaPods.

**Comment by kioshimafx** [comment]
Good idea @liruqi I'll do it today :+1:

**Comment by ex3ndr** [comment]
Do not close issues until they are fixed.

**Comment by ex3ndr** [comment]
Fixed in latest NYTPhotoViewer, will update soon.
