### ISSUE TITLE
Disabling notifications for separate contact/group doesn't work

### ISSUE THREAD

**Issue by xzenon** [actorapp/actor-platform#188]
In iOS (I believe Android should also be affected):

1. Open some dialog
2. Tap user avatar to open his profile
3. Disable "Notifications" switch to turn off Push notifications from this contact
4. When he sends you a message - you'll still receive Push notification

I found out that the following is defined in https://github.com/actorapp/actor-platform/blob/master/actor-server/actor-core/src/main/scala/im/actor/server/sequence/VendorPush.scala:
 
`def peerEnabled(deviceType: String, peer: Peer) = wrapEnabled(deviceType, s"chat.${peerStr(peer)}")`

but then never used in code so the option value is never taking into consideration when sending a Push.

**Comment by prettynatty** [comment]
will take a look on that soon
