### ISSUE TITLE
Fix join by link to group in which user already exists

### ISSUE THREAD

**Issue by olegshilov** [actorapp/actor-platform#236]

**Comment by Maay** [comment]
Link to the group I'm in and link to the group I'm not in both lead me to the app's home screen

**Comment by Maay** [comment]
Sometimes it freezes on the logo state

**Comment by Maay** [comment]
It should lead me to the group's chat in both scenarios

**Comment by Maay** [comment]
Reproduced even in chat I wasn't in: clicked the link, clicked the envelope, got to the blue screen, without  logo. While stayed at the blue screen, appeared at the group for other users. Refreshed the page, group appeared in the list.

**Comment by nkt** [comment]
Unable to implement expected behaviour due `ActorClient.joinGroupViaLink` returns error with message `User is already a member of the group.` instead of peer of the group.

**Comment by nkt** [comment]
Blocked by #722
