### ISSUE TITLE
Clicking on "Actor open source" group in web application makes almost every application component unusable

### ISSUE THREAD

**Issue by adfeno** [actorapp/actor-platform#295]
Steps to reproduce:

1.    Click on any other group or conversation **except** "Actor open source".
1.    Note that the conversation loads as expected.
1.    Click on "Actor open source".
1.   Show no conversation history, and you won't be able to see the messages you send.
1.    Every other conversation history won't be shown, and you won't be able to see the messages you send to those other conversations too.

Workaround (**not the solution**):

1.    Remove every character from the URI string **except** "app.actor.im", so that the web application reloads itself.
1.    Do everything as usual. Except that we mustn't open "Actor open source" group conversation.

**Comment by ex3ndr** [comment]
Fixed
