### ISSUE TITLE
Apt-get upgrade does not upgrade server

### ISSUE THREAD

**Issue by leo-goss** [actorapp/actor-platform#344]
Running on ubuntu 14.04, server version .120 would not upgrade to latest version. Fix was 
`apt-get remove actor` 
then 
`apt-get install actor`

**Comment by rockjam** [comment]
Hi, did you try this way?

```
sudo apt-get update
apt-get install --only-upgrade actor
```

**Comment by leo-goss** [comment]
I did! It was for some reason affecting .120, updated again now just fine. Worth looking into it anyway perhaps

**Comment by rockjam** [comment]
Okay. What version do you have now?
