### ISSUE TITLE
Missing some files when compile source code

### ISSUE THREAD

**Issue by bevalH** [actorapp/actor-platform#349]
Hi 
missing some files when i try to compile source code.  version 1.0.145  
like im.actor.server.model.Peer  and im.actor.server.model.PeerType,  but i found it in binary file actor-1.0.145.zip. where can i find these files?  
someone help me?  i really interested in this great project.

**Comment by prettynatty** [comment]
How you compile code? You should run `sbt compile`

**Comment by bevalH** [comment]
Hi prettynatty!  think you reply

i was compile code with sbt.  but  i found its already miss some files when i download source code in https://github.com/actorapp/actor-platform/archive/server/v1.0.145.tar.gz,

**Comment by rockjam** [comment]
Did you succeed to compile server?

**Comment by bevalH** [comment]
Hi rockjam:
compile failed .   when i compile code, it told me miss im.actor.server.model.Peer and im.actor.server.model.PeerType
how can i resole it ?
thank you reply

**Comment by rockjam** [comment]
is it the only error you get? can you paste all logging that you get when compiling it?

**Comment by bevalH** [comment]
Information:Modules "actor-models-build", "actor-session-build", "actor-persist-build", "actor-oauth-build", "actor-session-messages-build" and 6 others were fully rebuilt due to project configuration/dependencies changes
Information:2/2/16, 23:21 - Compilation completed with 10 errors and 0 warnings in 10s 658ms
/Users/beval/ActorPlatform/actor-projects/actor-server/actor-models/src/main/scala/im/actor/server/model/DialogId.scala
    Error:Error:line (3)not found: type PeerType
final case class DialogId(typ: PeerType, id: String)
                               ^
    Error:Error:line (6)not found: value PeerType
  def privat(id1: Int, id2: Int): DialogId = DialogId(PeerType.Private, id(id1, id2))
                                                      ^
    Error:Error:line (8)not found: value PeerType
  def group(id: Int): DialogId = DialogId(PeerType.Group, id.toString)
                                          ^
    Error:Error:line (11)value typ is not a member of im.actor.server.model.Peer
    peer.typ match {
         ^
    Error:Error:line (12)not found: value PeerType
      case PeerType.Private ⇒ privat(peer.id, clientUserId)
           ^
    Error:Error:line (12)value id is not a member of im.actor.server.model.Peer
      case PeerType.Private ⇒ privat(peer.id, clientUserId)
                                          ^
    Error:Error:line (13)not found: value PeerType
      case PeerType.Group   ⇒ group(peer.id)
           ^
    Error:Error:line (13)value id is not a member of im.actor.server.model.Peer
      case PeerType.Group   ⇒ group(peer.id)
                                         ^
    Error:Error:line (14)value typ is not a member of im.actor.server.model.Peer
      case _                ⇒ throw new RuntimeException(s"Wrong peer type ${peer.typ}")
                                                                                  ^
/Users/beval/ActorPlatform/actor-projects/actor-server/actor-models/src/main/scala/im/actor/server/model/PeerBase.scala
    Error:Error:line (4)not found: type PeerType
  val `type`: PeerType
              ^

**Comment by rockjam** [comment]
Well, it would be better if you gave me whole log, starting from point where you typed `sbt compile`. Another option for you is to clone our repo and build actor server from latest master. You can make it following way:
```
git clone git@github.com:actorapp/actor-platform.git
cd actor-platform/actor-server
sbt compile
```

**Comment by bevalH** [comment]
q:model beval$ sudo git clone git@github.com:actorapp/actor-platform.git
Password:
Cloning into 'actor-platform'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rockjam** [comment]
Well, do you have your public key added in github account?

**Comment by bevalH** [comment]
compile succeed ! there is no misstake
i think i know where i was wrong!  because i wanted bootstrap the server by Main.scala in IDE. 

thank you so much @rockjam @prettynatty

**Comment by rockjam** [comment]
@bevalH you are welcome. Closing as resolved.
