### ISSUE TITLE
Update actor-botkit to latest akka 2.4.2-RC1

### ISSUE THREAD

**Issue by joojic** [actorapp/actor-platform#367]
Maven actor-botkit has old akka dependencies - http://mvnrepository.com/artifact/im.actor/actor-botkit
I think because of this, bot's are not stable. Akka websocket connection has memory leak,  after some time all bot's hangups. 
This can be a source problem of - community server GateKeeper bot does not response time to time.

**Comment by rockjam** [comment]
@joojic fixed

**Comment by joojic** [comment]
Thanks!
