### ISSUE TITLE
False message reads in desktop app

### ISSUE THREAD

**Issue by rockjam** [actorapp/actor-platform#368]
In electron apps, when dialog is open, but app window is not visible new messages are read automatically. This behaviour is incorrect

**Comment by ex3ndr** [comment]
Did you marked as offline on other devices?

**Comment by rockjam** [comment]
Other devices are not active, android app could be working in background, if that matters. Problem seems to be in window.hidden(or something similar) behaviour in Electron.

**Comment by rockjam** [comment]
You can reproduce it in this branch: https://github.com/actorapp/actor-bootstrap/tree/desktop-debug

```
cd app-desktop
 ./build.sh
build/Actor-darwin-x64/Actor.app/Contents/MacOS/Electron //in terminal
```
Try to hide, minimize, show electron window, and watch logs

**Comment by rockjam** [comment]
@Maay is it a duplicate?
