### ISSUE TITLE
cannot get Activation Gateway token

### ISSUE THREAD

**Issue by silentred** [actorapp/actor-platform#403]
Hi,

I followed this [doc](https://developer.actor.im/docs/sms-gate). sent the `/start` to `@gatekeeper`, but the token was not received. Is free token still available now? Thanks

**Comment by rockjam** [comment]
@silentred Token creation via gatekeeper is still available, try it again please. Send /newtoken to gatekeeper to create a token

**Comment by silentred** [comment]
@rockjam , still got nothing, and there is only one check before each message. Is this a clue?

**Comment by silentred** [comment]
got the token, thanks. It takes some time to get the response.

**Comment by rockjam** [comment]
@silentred One check is fine, we don't mark reads and deliveries in dialogs with bots

**Comment by rockjam** [comment]
Closing this as resolved
