### ISSUE TITLE
Development environment setup?

### ISSUE THREAD

**Issue by NullPtrEx** [actorapp/actor-platform#407]
I have been studying the source code and I want to make some contributions, starting with small defects. I tried to setup the workspace with IntelliJ but ran into all sorts of problems. It would be very helpful if you could make a small video of how you setup your server workspace for development.

**Comment by rockjam** [comment]
@NullPtrEx are you familiar with [sbt](http://www.scala-sbt.org/)? server side source code is sbt project.

**Comment by NullPtrEx** [comment]
Yea I am familiar with SBT. I got all code to compile and imported into IntelliJ. I also have the Android, iOS and web apps apps running. What I am talking more about are things like:

1. Best practice for debugging the server. What environment variables to set and any tips.
2. Do you guys still use protob to generate? I read somewhere you guys have your own forked implementation?
3. Any other tips? For example I found you guys probably have a IntelliJ Live Template to convert => to a single unicode character etc. Maybe there's an exported settings.jar file for IntelliJ?

**Comment by rockjam** [comment]
@NullPtrEx well, best workflow for server development I came up with:
* run `sbt` in interactive mode in terminal. 
* compile server first. there will be a lot of "red code", cause some code is generated at compile time.
* trigger compile/update/test in sbt interactive console
* refresh Intellij Idea project only when you changed something important in your build(like dependency or project structure) cause refresh is pretty slow. 
* run tests to be sure you didn't broke anything
* write tests to make sure your feature works.

I rarely start server on my local machine. I make sure that everything works via tests, and sometimes run it on dev server.

Tests are in `actor-tests` subproject. So you basically run them via sbt interactive console like this:
```
project actor-tests
test //run all tests
testOnly *MessagingServiceSpec //to run single suite
```

We use "classic" protobuf inside server code. Our own implementation works in our rpc layer.  

Regarding => converting ⇒. It is handled by sbt scalariform plugin, which triggers each time you compile code. Basically, all formatting handled by sbt scalariform plugin. Intellij Idea settings we use for scala code are IDE defaults.

**Comment by NullPtrEx** [comment]
Thanks @rockjam! That's a lot of good info. I will do as you suggest.
