### ISSUE TITLE
Able to log in using web application, but no messages displayed

### ISSUE THREAD

**Issue by adfeno** [actorapp/actor-platform#435]
I have noticed this issue in 2016-03-18, however, I can't tell for sure when it really started.

# Steps to reproduce
1. Using any web browser, clear the entire cache and history.
2. Access your account with the web application deployed at App.Actor.IM.
3. After authentication, click on any discussion.

# Symptoms 
* Chat history doesn't load.
* Client does get new messages, but they're not shown in the chat history.
* Client does get notification sounds when receiving messages.
* Client cannot send messages as the input box also doesn't load.
* When clicking on a discussion, the notification that the client has read the messages is sent to the servers, causing the user to loose track of the messages he has really read.

Here is a log from the console of the GNU IceCat/IceWeasel browser (which is free software, as in freedom, and which is way superior than it's parent project, Firefox, this which is non-free software): 
[Console.log.txt](https://github.com/actorapp/actor-platform/files/181049/Console.log.txt)

# Notes
* Three or four authentications after experiencing this problem, I received a message from Actor security, but I cannot read anything.
* The above log file was made from the moment I enter App.Actor.IM prior to inserting the account information, to some seconds after clicking on the Actor security discussion.

**Comment by nkt** [comment]
@adfeno we've published new release. Please try again, your problem should be resolved.

**Comment by adfeno** [comment]
Thank you very much. :D

I just tried to authenticate and open a chat tab, and it seems to be 
working fine now. :D

**Comment by nkt** [comment]
Ok, I'm closing this. If you have another problems or questions, open another issue.
