### ISSUE TITLE
After changing my name it doesn't changes in any of the other person's clients

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#450]
In contact lists or chat. Photo and nick changes well.

**Comment by paykoob** [comment]
I found the problem. its not related to server. its a sdk problem. 
In "im.actor.core.modules.sequence.internal.GetDiffCombiner":

    } else if (false && u instanceof UpdateUserNameChanged) {  
        // Ignore
    } else {
        res.getOtherUpdates().add(u);
    }

it dose not occur when another person's client is open, it occurs when another person's app is closed. after reopening the app, he/she cant see the new name.

@ex3ndr! is there a reason for ignoring NameChanged?? 
anyway I remove "else" and this issue has been solved. (with minor cleaning on UserCommandHandler.scala)

**Comment by paykoob** [comment]
resolved by https://github.com/actorapp/actor-platform/pull/618
