### ISSUE TITLE
Localizable.strings should add "send" for compose bar

### ISSUE THREAD

**Issue by ljshj** [actorapp/actor-platform#52]
Localizable.strings should add "send" for compose bar.
For example,for Chinese:
"Send" = "发送";

**Comment by ljshj** [comment]
"Join public group" = "加入公众群" should be added too.

**Comment by ex3ndr** [comment]
We use "Send" text. May be you have some typo? We localized send button to russian already.

**Comment by ljshj** [comment]
No "Send" key in Localizable.strings, could you tell me where is the key? Thanks

**Comment by ex3ndr** [comment]
Sorry, i mean "ChatSend"
