### ISSUE TITLE
crash in android on 4.1.1 and 4.2.2 in loading avatar images

### ISSUE THREAD

**Issue by haajmahmoud** [actorapp/actor-platform#521]
related to fresco

**Comment by paykoob** [comment]
unfortunately I cant reproduce the bug. 
but it seems related to this: https://github.com/facebook/fresco/issues/1005

@ex3ndr  : upgrading fresco to 0.7.0 and add "com.facebook.fresco:webpsupport:0.9.0" is a good idea? 
(and okHttp to 2.6.0)

**Comment by Maay** [comment]
@kor-ka any ideas?
