### ISSUE TITLE
access hash big problem

### ISSUE THREAD

**Issue by haajmahmoud** [actorapp/actor-platform#526]
in  some situations accidentally bob has incorrect access hash of Alice 
and couldn't send message to her. or add Alice to a group. unless uninstall the app or clean cookies

**Comment by xzenon** [comment]
+1
Some users have such issue on a regular basis. Please investigate and fix.

**Comment by ex3ndr** [comment]
I thought that we have solved this issue, but it seems that appears again in our latest deployment.

**Comment by Maay** [comment]
Need to be reproduces, should be checked in master

**Comment by haajmahmoud** [comment]
it seems has been fixed. now our tester bug scenario doesn't occur in any version of androids.
issue can be closed.

**Comment by xzenon** [comment]
@haajmahmoud Could you show your test scenario please? How did you reproduce it (just want to check it by myself too)?

**Comment by ex3ndr** [comment]
Also in some cases it was client related bug and already solved in branch and will be merged before next release.
