### ISSUE TITLE
updates of notification big problem

### ISSUE THREAD

**Issue by haajmahmoud** [actorapp/actor-platform#527]
sometime app shows it is a some unread message. but its nothing in dialog list. and you should open all of dialogs to retrieve the messages.

**Comment by ex3ndr** [comment]
Related to Server

**Comment by haajmahmoud** [comment]
sometime there is no counter or notification at all (not in app badge icon, nor dialogs). 
but when we open some dialog, there is some new messages.

**Comment by ex3ndr** [comment]
Closing this issue as it will be fixed int #633 and #634
