### ISSUE TITLE
Notifications settings on iOS saves wrong value on the server

### ISSUE THREAD

**Issue by prettynatty** [actorapp/actor-platform#53]

**Comment by ljshj** [comment]
iOS push notification can only be received one time after install and sign in.

**Comment by ljshj** [comment]
When I go into the conversion view, the push notification will disapear forever.

**Comment by ljshj** [comment]
When ios can received after install and sign in, it push first conversation‘s message always. For example, user A is using ios app, and A and B in the group AB; then user B send message "moon", the "moon" is pushed to ios; then user B go into group AB, send message "sun", the "moon" is pushed to ios forever.
