### ISSUE TITLE
Vertical and horizontal centering of icons star, quote, phone icons in my profile screen

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#598]

**Comment by Maay** [comment]
Move them please from upper left corner
![image](https://cloud.githubusercontent.com/assets/159617/14377654/9bb52a08-fd79-11e5-939d-8b286d19cbeb.png)

to the vertical center, something like that
![image](https://cloud.githubusercontent.com/assets/159617/14377810/75c52b80-fd7a-11e5-9bdb-b2269976af15.png)

**Comment by kor-ka** [comment]
![image](https://cloud.githubusercontent.com/assets/2598970/14380643/4ae0e2ec-fd89-11e5-89aa-28e3cbc3a24e.png)
