### ISSUE TITLE
Upgrade to Caffeine 2.x

### ISSUE THREAD

**Issue by ben-manes** [actorapp/actor-platform#624]
The current version is 2.2.6 and this project is on 1.2.0. It would be nice to upgrade to be on the latest major version. As an incentive, you'll also get [higher hit rates](https://github.com/ben-manes/caffeine/wiki/Efficiency).

There was a minor API change in v2 (simpler removal listener syntax), but that appears to be a non-issue in your usages.

**Comment by rockjam** [comment]
@ben-manes thanks for your attention. It seems that 2.2.6 don't have any breaking changes(for us). Going to test it some more tomorrow.

**Comment by rockjam** [comment]
Done
