### ISSUE TITLE
bug: some times bob sees alice's message and reply to it, but there is no seen symbol in alice's dialog.

### ISSUE THREAD

**Issue by haajmahmoud** [actorapp/actor-platform#631]
![screenshot_2016-04-11-10-40-37](https://cloud.githubusercontent.com/assets/18291085/14457818/88cb5614-00c2-11e6-91b6-da9323392d19.png)

**Comment by Maay** [comment]
@ex3ndr Steve, can you please give some info to decide: us or Iranian team and how exactly.
