### ISSUE TITLE
Which class in java api is responsible for sending a package (or message)?

### ISSUE THREAD

**Issue by elgolondrino** [actorapp/actor-platform#67]
Hi, Andrey!
First of all, sorry for disturbing you!
I'm confused with source code study...! As far as I'm aware class "Messenger" is responsible for sending package to remote peer isn't it? And so far it ends with "EnvelopeCollection" (actor-apps/core/src/main/java/im/actor/model/droidkit/actors/mailbox/collections) which is then "envelopes.putEnvelope(envelope, time)" in mailBox. But this method returns "long type" and I don't see or can't figure out any output stream to be send to peer can you please guide me through how that all stuff works...? I want to understand it, how that Simple package formed end send to the client? 

P.S.
Заранее спасибо Андрей, буду признателень если поможете!
My email is elvecenjo24@gmail.com.

**Comment by prettynatty** [comment]
cc @ex3ndr @kor-ka
