### ISSUE TITLE
Fulfill core-js API

### ISSUE THREAD

**Issue by prettynatty** [actorapp/actor-platform#72]
* Creation date
* Change favicon on message

**Comment by prettynatty** [comment]
cc @olegshilov

**Comment by olegshilov** [comment]
* Global app settings
* Conversation description

**Comment by olegshilov** [comment]
Use `window.setNotificationFavicon()` to change favicon on notifications.

**Comment by olegshilov** [comment]
* Online status of group members
* Count group's shared media.
* Set group photo
* Set user photo
* Upload progress

**Comment by prettynatty** [comment]
cc @ex3ndr
