### ISSUE TITLE
"Read" status icons sometimes showing wrong statuses

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#721]
![image](https://cloud.githubusercontent.com/assets/159617/14683984/4ca44ad6-0736-11e6-89b2-7756c45d135b.png)
It also might show wrong statuses after reload before changing the chat room

**Comment by Maay** [comment]
@nkt is saying this is the library issue

**Comment by ex3ndr** [comment]
Probabbly app thinks that you are offline. This is the case when our IDLE timer fired. When you enter text in chrome it captures key pressed events and we can't handle that someone is actually using app and we decided to go offline.

**Comment by ex3ndr** [comment]
Very unclear bug, one related bug was solved on server and one in app on future problems, open new bug with exact reproduction steps.
