### ISSUE TITLE
Push notifications don't come 

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#804]

**Comment by rockjam** [comment]
Need checking

**Comment by ezze** [comment]
Is it fixed? I stop receiving notifications on Android when I was inactive for some time.

**Comment by ezze** [comment]
Tested again...

Everything was fine until I left my Android devices with locked screens and send a message from one of them to another more than an hour later (message is checked once on sending device). Notification didn't come again on receiving device though I see Actor in running applications. I see new messages only when I open Actor window (then message is checked twice on sending device). After that I receive all notifications again.

Is such behavior expected?

**Comment by rockjam** [comment]
@ezze No, this behaviour is not correct. I can't tell a reason for sure. We still experience problems with push notifications sometimes - this is server side bug, and we are trying to achieve stable work of push notifications. I can't tell anything about client-side though
