### ISSUE TITLE
use xcode import error on cocospod

### ISSUE THREAD

**Issue by winneryong** [actorapp/actor-platform#81]
in actor-platform-master/actor-apps/app-ios directory 
execute "pod update" command encounter error ，detail below：

[!] Unable to read the license file `/Users/mac/Downloads/actor-platform-master/actor-apps/app-ios/Pods/j2objc-local/LICENSE` for the spec `j2objc-local (0.9.7)`

[!] Unable to read the license file `/Users/mac/Downloads/actor-platform-master/actor-apps/app-ios/Pods/j2objc-local/LICENSE` for the spec `j2objc-local (0.9.7)`

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `ActorApp` to `Pods/Target Support Files/Pods-ActorApp/Pods-ActorApp.debug.xcconfig` or include the `Pods/Target Support Files/Pods-ActorApp/Pods-ActorApp.debug.xcconfig` in your build configuration.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `ActorApp` to `Pods/Target Support Files/Pods-ActorApp/Pods-ActorApp.release.xcconfig` or include the `Pods/Target Support Files/Pods-ActorApp/Pods-ActorApp.release.xcconfig` in your build configuration.

**Comment by ex3ndr** [comment]
All this things are warrings, you can just easily ignore it
