### ISSUE TITLE
Formatter Messages / Rendering Support

### ISSUE THREAD

**Issue by sirinath** [actorapp/actor-platform#87]
Please add functionality to write own rendering. E.g. you want to share a product spec sheet. This can be encoded as JSON, XML, YAML, etc. which can be sent as an attachment but will render in the message with image and detail based on available area.

**Comment by PerfectCarl** [comment]
Would it render link to web resource in a more convenient way?
Like displaying a thumbnail and title for video (youtube/vimeo/twitch) and music (spotifiy)?

Or should my feature request be filed as a separate one?
