### ISSUE TITLE
Server as UnZip and run file

### ISSUE THREAD

**Issue by sirinath** [actorapp/actor-platform#90]
Can you package the server and download, unzip and run distribution than building it or using docker.

**Comment by rockjam** [comment]
I don't understand what you actually need. Do you need server's docker image?

**Comment by sirinath** [comment]
Can you have just a batch file and the Jar which you can download (mabe packed as a Jar) which you can download and run.

**Comment by rockjam** [comment]
We have a docker image, which you can run following this manual https://actor.readme.io/docs/server-docker
