### ISSUE TITLE
iOS App - fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by a7am** [actorapp/actor-platform#910]
When trying to run the iOS app on iPhone from xcode7, a fatal error rises:
`fatal error: unexpectedly found nil while unwrapping an Optional value`
The error has risen from the "Bundle.swift" file, on the following line:
`let frameworkBundle = NSBundle(identifier: "im.actor.ActorSDK")!`
App installs successfully and the error comes a few seconds after the application launch on the device.
Any ideas?

**Comment by jamesbond12** [comment]
you changed your bundle name. thats why

**Comment by a7am** [comment]
I get it. Thanks.
