### ISSUE TITLE
iOS App - "ipa" file for actor platform iOS app cannot be distributed on web platforms

### ISSUE THREAD

**Issue by a7am** [actorapp/actor-platform#926]
I've experienced an issue with deploying the iOS app from platform, not bootstrap, into web platforms such as hockeyapp for distribution.
I need to be able to customize many different parts of this app, so I need to work with the platform version of this app and as mentioned in the github issue #165 , it can't be archived. But I need to be able to both archive and deploy the app for distribution to some testers, so I need to archive it and it is not possible. I was wondering if it is possible or if you could tell me how can major changes be done in bootstrap project, I mean changing every available file as it is possible in platform version.

I tried a possible alternative myself when I tried to just build the app for "Generic device" and not archive it. It was built successfully but when downloaded from the online platform and installed, It showed me an error which I have pasted from the Xcode console:
 
`<Warning>: [ApplicationWorkspace]: Failed to install application: <#Bundle Identifier I have set for myself>; /var/mobile/Media/Downloads/-125812920774240990/-1854675441164754719; Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620393, ErrorDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.9URN3U/extracted/Payload/ActorApp.app/Frameworks/CocoaAsyncSocket.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)}`
 
I think it has something to do with signing of the ActorSDK which is integrated into ActorApp. What is the process needed to correctly sign and distribute the "platform" version?
By the way, this app can be directly uploaded to an iPhone connected to the computer and Xcode, but does not send or download any media!!!
I am using the latest clone of the platform and the latest cocoapods.

**Comment by jamesbond12** [comment]
you cant archive actor-platform ios app ever. make your changes and run ./buildFramework.sh to create framework. copy this framework to bootstrap. thats all

**Comment by ex3ndr** [comment]
try to use actor-bootstrap instead

**Comment by a7am** [comment]
I built he ActorSDK.framework for generic device and replaced it with the one in bootstrap app and got the result.
Thanks

**Comment by lilac** [comment]
@amostajabi Could you elaborate how you replace the framework? The sdk is added as a coacopod dependency, right? Do you replace the pod or the file itself?
