### ISSUE TITLE
On firefox, the top banner (Welcome to actor network) hides the bottom of the screen in the web chat

### ISSUE THREAD

**Issue by PerfectCarl** [actorapp/actor-platform#93]
When in the web chat using Firefox 39 on linux, a top banner is displayed inviting me to use the applications on android and IOS.

Unfortunately, this banner makes the whole screen scrolls and hides the bottom of the page cutting the input zone and the buttons to add files and photos.

Everything works fine on chrome

**Comment by rockjam** [comment]
Can you provide screenshot of this?

**Comment by vkotovv** [comment]
Reported earlier here: #65. There is a screenshot.

**Comment by rockjam** [comment]
This issue was solved in latest web client, as far as i remember. Can you give a screenshot of whole screen, not just dialog window

**Comment by vkotovv** [comment]
Looks good, works ok for me now. Input zone is visible even with banner.

**Comment by PerfectCarl** [comment]
Here's a screenshot of the issue
![Imgur](http://i.imgur.com/g10xO8c.png)

Is the issue supposed to be fixed on app.actor.im?

**Comment by rockjam** [comment]
@PerfectCarl  can you clean browser's cache and try again?

**Comment by PerfectCarl** [comment]
It's fixed indeed.
Thanks!
