### ISSUE TITLE
Add the possibility to edit your own previous messages

### ISSUE THREAD

**Issue by PerfectCarl** [actorapp/actor-platform#94]
It would very useful for me and my friends to be able to edit our own messages (seeing how we are not skilled typists).

Some other chat apps have this (whatsapp and skype) and I miss the feature while using actor

**Comment by ex3ndr** [comment]
Whatsapp Doesn't support this.

**Comment by PerfectCarl** [comment]
> Whatsapp Doesn't support this.
You are right about this. Maybe it was a special build of whatsapp or I dreamt the feature altogether.

This feature would be still killer for me (and friends)

**Comment by nickbuddendotcom** [comment]
+1. I don't think our team will use actor without this.

**Comment by rockjam** [comment]
Done
