### ISSUE TITLE
Android app notification problem

### ISSUE THREAD

**Issue by ahAnsari** [actorapp/actor-platform#955]
In using android app no notification is received after app is removed from recent apps.App's process is closed but app's service is still running.
I have tested this on 3 android devices

**Comment by rockjam** [comment]
@ahAnsari Thanks for report. We have problems with connection to GCM now, hope to fix it soon

**Comment by ahAnsari** [comment]
Thanks for your answer.

**Comment by rockjam** [comment]
@ahAnsari should be fine by now, closing this one
